'use strict';
const $ = (s) => document.querySelector(s);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label = s => String(s).replaceAll('_',' ');
const external = u => {try {const a=new URL(u); return ['http:','https:'].includes(a.protocol)?a.href:'#';}catch{return '#';}};
const link = (u,t) => `<a href="${esc(external(u))}" target="_blank" rel="noopener noreferrer">${esc(t||u)} ↗</a>`;
const formatDate = d => d ? new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not reported';
const formatAmount = value => {const [whole,fraction] = String(value).split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(fraction!==undefined?'.'+fraction:'');};
const PAGE_SIZE=100;
let companies=[], current=null, activeTab='overview', selected=null, compare=[], visibleCompanies=PAGE_SIZE;
const claim = field => current?.claims.find(c=>c.field===field);
const fields = families => current.claims.filter(c=>families.includes(c.family));
// Data layer: the run's static report (window.FJ_INDEX + lazily loaded chunks, works from file://)
// or the local server API. Both return the same envelope shapes.
const STATIC = typeof window.FJ_INDEX !== 'undefined';
function loadChunk(n){return new Promise((resolve,reject)=>{if(window.FJ_CHUNKS&&window.FJ_CHUNKS[n])return resolve();const s=document.createElement('script');s.src=`data/chunk-${String(n).padStart(4,'0')}.js`;s.onload=()=>resolve();s.onerror=()=>reject(new Error('Could not load data chunk'));document.head.appendChild(s);});}
async function getCompany(org){if(!STATIC)return fetch(`/api/company/${encodeURIComponent(org)}`).then(r=>r.json());const row=window.FJ_INDEX.find(r=>r.organisation_number===org);if(!row)throw new Error('Unknown company');await loadChunk(row.chunk);return window.FJ_CHUNKS[row.chunk][org];}
async function getCompanies(){return STATIC?{companies:window.FJ_INDEX,stats:window.FJ_STATS}:fetch('/api/companies').then(r=>r.json());}
const ASK_MAP=[[/financ|revenue|profit|assets|equity|debt|regnskap|omsetning|numbers/i,['financials']],[/lead|ceo|board|director|manage|leder|styre|runs/i,['leadership']],[/job|hir|career|stilling|recruit|working/i,['hiring']],[/news|activ|announc|nyhet/i,['activity']],[/where|location|office|address|workplace|operat/i,['locations']],[/web|social|linkedin|contact|site/i,['website','contact','social_profiles']],[/what|does|describe|business|employee|industry/i,['identity','description','workforce']]];
function localAnswer(p,q){if(/chang|refresh|update/i.test(q))return{answer:`${p.changes.length} change record(s) against the previous run.`,claims:[]};const fam=new Set();ASK_MAP.forEach(([re,f])=>{if(re.test(q))f.forEach(x=>fam.add(x));});if(!fam.size)return{answer:'This question is not supported by the captured company facts. Ask about financials, leadership, locations, hiring, activity, or changes.',claims:[]};const claims=p.claims.filter(c=>fam.has(c.family));const availability={};fam.forEach(f=>{if(p.availability[f])availability[f]=p.availability[f];});return{answer:claims.length?`Found ${claims.length} supported claim(s) in the selected profile.`:'The captured sources do not establish an answer.',claims,availability};}
async function askApi(org,q){return STATIC?localAnswer(current,q):fetch(`/api/ask?org=${encodeURIComponent(org)}&q=${encodeURIComponent(q)}`).then(r=>r.json());}
const latestClaim=(p,field,scope='legal_entity')=>p.claims.filter(c=>c.field===field&&(c.scope===scope||!c.reporting_period)).sort((a,b)=>String(b.reporting_period?.tilDato||'').localeCompare(String(a.reporting_period?.tilDato||'')))[0];
function valueHTML(v){
  if(v===null||v===undefined) return '<span class="subtle">Not reported</span>';
  if(typeof v==='boolean') return v?'Yes':'No';
  if(Array.isArray(v)) return v.map(valueHTML).join('<br>');
  if(typeof v==='object') {
    if('amount' in v) return `<span class="money">${esc(formatAmount(v.amount))} <small>${esc(v.currency)}</small></span><span class="subtle">${esc(v.account_type)} · Amount in currency units</span>`;
    return `<div class="data-list">${Object.entries(v).filter(([k])=>!['record_id','independent_sentiment'].includes(k)).map(([k,x])=>`<div class="data-pair"><span>${esc(label(k))}</span><span>${k==='url'?link(x,'Open source'):valueHTML(x)}</span></div>`).join('')}</div>`;
  }
  return esc(v);
}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,2400);}
function renderList(){
  const q=$('#search').value.toLowerCase(), filter=$('#filter').value, sort=$('#sort').value;
  let rows=companies.filter(c=>(`${c.name} ${c.organisation_number} ${c.city} ${c.industry}`).toLowerCase().includes(q));
  if(filter==='verified') rows=rows.filter(c=>c.website_verified);
  if(filter==='changed') rows=rows.filter(c=>c.changes);
  rows.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name):sort==='employees'?(a,b)=>(b.employees??-1)-(a.employees??-1):(a,b)=>b.claim_count-a.claim_count);
  $('#result-count').textContent=rows.length;
  $('#company-list').innerHTML=rows.length?rows.slice(0,visibleCompanies).map(c=>`<button class="company-row ${selected===c.organisation_number?'active':''}" data-company="${esc(c.organisation_number)}"><div class="row-top"><span class="initial">${esc(c.name.slice(0,1))}</span><div><div class="row-title">${esc(c.name)}</div><div class="row-meta">${esc(c.organisation_number)} · ${esc(c.city)}</div></div></div><div class="row-footer">${c.website_verified?'<span class="verified-tag">✓ Verified site</span>':''}${c.hiring?'<span class="verified-tag">Hiring</span>':''}<span>${c.claim_count} sourced claims</span></div></button>`).join(''):'<div class="empty">No companies match this search.</div>';
  if(!$('#list-pagination')) $('#company-list').insertAdjacentHTML('afterend','<div class="list-pagination" id="list-pagination"></div>');
  const shown=Math.min(visibleCompanies,rows.length), remaining=rows.length-shown;
  $('#list-pagination').innerHTML=`<span aria-live="polite">Showing ${shown.toLocaleString()} of ${rows.length.toLocaleString()}</span>${remaining?`<button class="button" id="load-more" aria-controls="company-list">Load ${Math.min(PAGE_SIZE,remaining)} more ↓</button>`:''}`;
}
async function selectCompany(org){
  selected=org; renderList();
  const data=await getCompany(org);
  if(selected!==org)return;
  current=data;activeTab='overview';renderProfile();
  try{history.replaceState(null,'',`#org=${encodeURIComponent(org)}${compare.length?`&compare=${compare.join(',')}`:''}`);}catch{}
}
function renderProfile(){
  const p=current, verified=p.availability.website.state==='available', identity=p.legal_identity||{};
  const hasIdentity=typeof identity.name==='string'&&Boolean(identity.name.trim()), staleIdentity=Boolean(identity.stale||claim('legal_name')?.stale);
  const badge=!hasIdentity?'Identity unavailable':staleIdentity?'Registry identity · stale':verified?'✓ Exact website match':'Registry identity';
  const address=claim('registered_address')?.value, industry=claim('industry')?.value;
  $('#profile').innerHTML=`<div class="profile-header"><div class="profile-kicker"><span class="eyebrow">COMPANY DOSSIER / ${esc(p.organisation_number)}</span><span class="pill ${verified&&hasIdentity&&!staleIdentity?'':'muted'}">${badge}</span></div><h2 class="company-name">${esc(hasIdentity?identity.name:p.organisation_number)}</h2><div class="identity-line">${esc(identity.legal_form||'')} · ${esc(address?.poststed||'Location not reported')} · Norway<br>${esc(industry?.beskrivelse||'Industry not reported')}</div><div class="profile-actions">${verified?`<a class="button primary" href="${esc(external(claim('official_website')?.value))}" target="_blank" rel="noopener">Visit company website ↗</a>`:''}<button class="button" id="compare-button">＋ Compare company</button><button class="button" id="download-profile">Export profile ↓</button></div></div><nav class="tabs" aria-label="Profile sections">${['overview','financials','people','activity','evidence','changes'].map(t=>`<button class="tab ${activeTab===t?'active':''}" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav><div class="tab-content" id="tab-content"></div>`;
  renderTab();
}
function citation(c){return c?`<button class="cite" data-claim="${c.id}" aria-label="Inspect supporting evidence">↗</button>`:'';}
function claimCard(c){return `<div class="claim-card"><div class="claim-head"><h4>${esc(label(c.field))}</h4><span class="state ${c.stale?'':'available'}">${c.stale?'Last known':'Sourced'}</span></div><div class="claim-value">${valueHTML(c.value)}</div><div class="claim-meta"><span>${esc(label(c.scope))}</span>${c.reporting_period?`<span>${esc(c.reporting_period.fraDato)} → ${esc(c.reporting_period.tilDato)}</span>`:''}${c.effective_at?`<span>Effective ${esc(c.effective_at)}</span>`:''}<button data-claim="${c.id}">Inspect ${c.evidence_ids.length} source${c.evidence_ids.length===1?'':'s'} ↗</button></div></div>`;}
function emptyFamily(f){const s=current.availability[f];return `<div class="notice"><b>${esc(label(s.state))}.</b> ${esc(s.reason)}</div>`;}
function renderTab(){
  const p=current, out=$('#tab-content');
  document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab));
  if(activeTab==='overview'){
    const factFields=[['employees','Registered employees'],['founded_on','Founded'],['registered_address','Registered address'],['latest_filing_year','Latest filed year']];
    const s=p.summary||{}, cite=ids=>(ids||[]).slice(0,3).map(id=>citation(p.claims.find(c=>c.id===id))).join('');
    const answered=(p.answers||[]).map(a=>`<div class="summary-section"><h4>${esc(a.question)}</h4><p>${esc(a.answer)}${cite(a.claim_ids)}</p></div>`).join('');
    const sections=(s.sections||[]).map(sec=>`<div class="summary-section"><h4>${esc(sec.title)}</h4>${sec.sentences.map(x=>`<p>${esc(x.text)}${cite(x.claim_ids)}${x.stale?' <span class="state">Last known</span>':''}</p>`).join('')}</div>`).join('');
    const legacy=(s.sentences||[]).slice(0,6).map(x=>`<p>${esc(x.text)}${cite(x.claim_ids)}</p>`).join('');
    const unknowns=(s.unknowns||[]).filter(u=>u.text).map(u=>`<li>${esc(u.text)}</li>`).join('');
    out.innerHTML=`<div class="block-title"><h3>The company, in context</h3><span class="subtle">Every sentence cites its sources ↗</span></div><div class="summary">${s.brief&&s.brief.text?`<p class="brief">${esc(s.brief.text)}</p>`:''}${sections||legacy||'<p>The captured sources do not establish a company summary.</p>'}</div>${answered?`<div class="block-title"><h3>Standard questions</h3><span class="subtle">Answered only from cited claims</span></div><div class="summary">${answered}</div>`:''}${unknowns?`<div class="block-title"><h3>What we could not establish, and why</h3><span class="subtle">Missing is never zero</span></div><ul class="unknowns">${unknowns}</ul>`:''}<div class="key-facts">${factFields.map(([field,title])=>{const c=claim(field);return `<div class="fact"><div class="fact-label">${title}</div><div class="fact-value">${field==='registered_address'&&c?esc([...(c.value.adresse||[]),c.value.postnummer,c.value.poststed].filter(Boolean).join(', ')):valueHTML(c?.value)}${citation(c)}</div></div>`;}).join('')}</div><div class="block-title"><h3>What we could establish</h3><span class="subtle">${p.claims.length} claims · ${p.evidence.length} evidence records</span></div><div class="health-grid">${Object.entries(p.availability).map(([family,s])=>`<div class="health-row" title="${esc(s.reason)}"><span>${esc(label(family))}</span><span class="state ${s.state}">${esc(label(s.state))}</span></div>`).join('')}</div>${askBox()}`;
  } else if(activeTab==='financials'){
    out.innerHTML='<div class="block-title"><h3>Filed financial results</h3><span class="subtle">Original currencies & reporting periods</span></div><div class="notice">Company and consolidated accounts are labelled separately. Missing values are not zero.</div>'+ (fields(['financials']).map(claimCard).join('')||emptyFamily('financials')) + '<div class="section-gap">'+fields(['filing_history']).map(claimCard).join('')+'</div>';
  } else if(activeTab==='people'){
    out.innerHTML='<div class="block-title"><h3>Registered leadership & workplaces</h3><span class="subtle">Official company-centric records</span></div>'+(fields(['leadership','locations','group']).map(claimCard).join('')||emptyFamily('leadership'));
  } else if(activeTab==='activity'){
    out.innerHTML='<div class="block-title"><h3>Public signals</h3><span class="subtle">Company-reported, dated where available</span></div>'+['hiring','activity','social_profiles','contact'].map(f=>`<h3 class="section-gap">${esc(label(f))}</h3>${fields([f]).map(claimCard).join('')||emptyFamily(f)}`).join('');
  } else if(activeTab==='evidence'){
    out.innerHTML=`<div class="block-title"><h3>Every claim has a trail</h3><span class="subtle">${(p.source_snapshot_count??p.source_snapshots.length)} saved response records</span></div><div class="notice">Select a claim to inspect its source URL, retrieval time, extraction selector, and content hash. Website claims require an exact legal identity match.</div>${p.claims.map(c=>`<div class="source-row"><div><b>${esc(label(c.field))}</b><div class="source-details">${esc(c.family)} · ${formatDate(c.last_observed_at)}${c.stale?' · stale':''}</div></div><button class="button" data-claim="${c.id}">Inspect ↗</button></div>`).join('')}`;
  } else {
    out.innerHTML=`<div class="block-title"><h3>Material changes</h3><span class="subtle">${p.changes.length} recorded</span></div>${p.refresh.previous_run_id?`<p class="subtle">Compared with ${esc(p.refresh.previous_run_id)}</p>`:'<div class="notice">This is an initial observation. A refresh with a previous run is needed to establish changes.</div>'}${p.changes.map(c=>`<div class="claim-card"><h4>${esc(label(c.field))} · ${esc(c.type)}</h4><div class="data-pair"><span>Previous</span><span>${valueHTML(c.previous_value)}</span></div><div class="data-pair"><span>Current</span><span>${valueHTML(c.current_value)}</span></div></div>`).join('')}${p.refresh.stale_claim_ids.length?`<div class="notice">${p.refresh.stale_claim_ids.length} last-known claim(s) retained because fresh supporting evidence was unavailable. They are not counted as business changes.</div>`:''}`;
  }
}
function askBox(){return '<section class="ask-box"><h3>Ask the evidence</h3><p>Answers use this company’s saved claims and sources.</p><form class="ask-form" id="ask-form"><input id="question" aria-label="Question about this company" placeholder="What do we know about this company?" required><button class="button primary" type="submit">Ask ↗</button></form><div class="ask-chips">'+['Who leads it?','Is it hiring?','What changed?'].map(q=>`<button class="chip" data-question="${esc(q)}">${q}</button>`).join('')+'</div><div class="answer" id="answer" aria-live="polite"></div></section>';}
async function askQuestion(q){$('#question').value=q;$('#answer').textContent='Checking the captured evidence…';const org=current.organisation_number;try{const r=await askApi(org,q);if(current.organisation_number!==org)return;$('#answer').innerHTML=esc(r.answer)+(r.claims||[]).slice(0,5).map(claimCard).join('')+(r.availability?Object.entries(r.availability).filter(([,s])=>s.state!=='available').map(([f,s])=>`<p>${esc(label(f))}: ${esc(s.reason)}</p>`).join(''):'');}catch{$('#answer').textContent='Could not read the saved profile. Please try again.';}}
function showEvidence(id){const c=current.claims.find(c=>c.id===id);if(!c)return;$('#evidence-content').innerHTML=`<h3>${esc(label(c.field))}</h3><div class="claim-value">${valueHTML(c.value)}</div>${c.evidence_ids.map(id=>{const e=current.evidence.find(e=>e.id===id);if(!e)return '';return `<section class="evidence-block">${link(e.source_url)}<div class="source-details">Retrieved ${esc(e.retrieved_at)} · ${esc(label(e.source_class))}${e.quote_kind?` · ${esc(label(e.quote_kind))}`:''}</div><pre>${esc(e.claim_span)}</pre><div class="hash">CONTENT SHA-256<br>${esc(e.content_sha256)}<br><br>SELECTOR<br>${esc(JSON.stringify(e.selector))}<br><br>EXTRACTION<br>${esc(e.extraction_method)}</div>${e.identity_proof?`<div class="notice">Identity method: ${esc(e.identity_proof.method)}<br>${esc(e.identity_proof.reason||'Exact organisation number in official registry endpoint')}</div>`:''}</section>`;}).join('')}`;$('#evidence-dialog').showModal();}
async function renderCompare(){const panel=$('#compare-panel');panel.hidden=!compare.length;if(!compare.length)return;const rows=await Promise.all(compare.map(org=>getCompany(org)));const money=c=>c&&c.value&&typeof c.value==='object'&&'amount' in c.value?`${formatAmount(c.value.amount)} ${c.value.currency}`:null;const role=(p,code)=>p.claims.filter(c=>c.field==='registered_role'&&c.value&&c.value.role_code===code).map(c=>c.value.name).join(', ')||null;const ratio=p=>{const e=latestClaim(p,'financial_equity'),a=latestClaim(p,'financial_assets');if(!e||!a)return null;const x=Number(e.value.amount)/Number(a.value.amount)*100;return isFinite(x)?x.toFixed(1)+'% (calculated)':null;};const facts=[['Industry',p=>latestClaim(p,'industry')?.value?.beskrivelse],['Legal form',p=>latestClaim(p,'legal_form')?.value],['Registered employees',p=>latestClaim(p,'employees')?.value],['Revenue (company accounts)',p=>money(latestClaim(p,'financial_revenue'))],['Operating result',p=>money(latestClaim(p,'financial_operating_profit'))],['Annual result',p=>money(latestClaim(p,'financial_net_profit'))],['Equity',p=>money(latestClaim(p,'financial_equity'))],['Equity ratio',ratio],['Reporting period',p=>{const c=latestClaim(p,'financial_revenue');return c?.reporting_period?`${c.reporting_period.fraDato} → ${c.reporting_period.tilDato}`:null;}],['Chief executive',p=>role(p,'DAGL')],['Board chair',p=>role(p,'LEDE')],['Verified website',p=>latestClaim(p,'official_website')?.value],['Registered workplaces',p=>p.claims.filter(c=>c.field==='registered_workplace').length||null],['Job ads (NAV feed and company site)',p=>p.claims.filter(c=>c.field==='job_posting').length||null],['Sourced claims',p=>p.claims.length]];panel.innerHTML=`<div class="comparison-head"><h2>Compare sourced facts</h2><button class="button" id="clear-compare">Clear comparison</button></div><div class="table-scroll"><table><thead><tr><th>Company fact</th>${rows.map(p=>`<th>${esc(p.legal_identity?.name||p.organisation_number)}<div class="source-details">${esc(p.organisation_number)}</div></th>`).join('')}</tr></thead><tbody>${facts.map(([name,fn])=>`<tr><td>${esc(name)}</td>${rows.map(p=>{let v=null;try{v=fn(p);}catch{}return `<td>${v===null||v===undefined||v===''?'<span class="subtle">Not found</span>':(typeof v==='string'&&/^https?:/.test(v)?link(v,v):esc(v))}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;try{history.replaceState(null,'',`#${selected?`org=${encodeURIComponent(selected)}&`:''}compare=${compare.join(',')}`);}catch{}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='load-more'){const previous=visibleCompanies;visibleCompanies+=PAGE_SIZE;renderList();const next=$('#company-list').querySelectorAll('[data-company]')[previous];if(next){next.focus({preventScroll:true});next.scrollIntoView({block:'nearest'});}return;}if(b.dataset.company)selectCompany(b.dataset.company).catch(()=>toast('Could not load company'));if(b.dataset.tab){activeTab=b.dataset.tab;renderTab();}if(b.dataset.claim)showEvidence(b.dataset.claim);if(b.dataset.question)askQuestion(b.dataset.question);if(b.id==='close-evidence')$('#evidence-dialog').close();if(b.id==='compare-button'){if(!compare.includes(selected)){if(compare.length===3)return toast('Compare up to three companies at a time');compare.push(selected);}renderCompare();toast(`${compare.length} company selected for comparison below`);}if(b.id==='clear-compare'){compare=[];renderCompare();}if(b.id==='download-profile'){const u=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`fjordlens-${selected}.json`;a.click();URL.revokeObjectURL(u);}});
document.addEventListener('submit',e=>{if(e.target.id==='ask-form'){e.preventDefault();askQuestion($('#question').value);}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus();}});
['search','filter','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>{visibleCompanies=PAGE_SIZE;$('#company-list').scrollTop=0;renderList();}));
getCompanies().then(({companies:c,stats:s})=>{companies=c;$('#stat-profiles').textContent=s.profiles.toLocaleString();$('#stat-claims').textContent=s.claims.toLocaleString();$('#stat-sites').textContent=s.verified_sites.toLocaleString();$('#stat-date').textContent=formatDate(s.retrieved_at);renderList();const h=new URLSearchParams(location.hash.slice(1));const want=h.get('compare');if(want){compare=want.split(',').filter(o=>c.some(r=>r.organisation_number===o)).slice(0,3);renderCompare().catch(()=>toast('Could not load comparison'));}const org=h.get('org')&&c.some(r=>r.organisation_number===h.get('org'))?h.get('org'):(c.length?c[0].organisation_number:null);if(org)return selectCompany(org);}).catch(()=>{$('#company-list').innerHTML='<div class="empty">Could not load the collection. Open the report written by a completed run, or start the server with an envelopes file.</div>';});
